# overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind:       Kustomization

resources:
  - ../../base

namespace: expense-staging

images:
  - name:    uptimecrew/expense-api
    newName: uptimecrew/expense-api
    newTag:  1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f1f

replicas:
  - name:  expense-api
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: expense-api-config
    patch: |-
      - op: replace
        path: /data/SPRING_PROFILES_ACTIVE
        value: staging
      - op: replace
        path: /data/LOG_LEVEL
        value: INFO
  - target:
      kind: Namespace
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-1"
